#!/bin/bash

function check-command {
  type $1 > /dev/null 2>/dev/null

  if [ $? -ne 0 ]
  then
    (>&2 echo "Command $1 expected, but not found.")
    (>&2 echo "Please install dependencies: sudo apt-get install sqlite3 jq")
    exit 1
  fi
}

function check-working-directory {
  if [ ! -d ~/.pomodoro_manager ]
  then
    mkdir ~/.pomodoro_manager
    echo '{
      "pomodoro_duration": "25m",
      "break_duration": "5m",
      "long_break-duration": "15m"
    }' > ~/.pomodoro_manager/config.json

    mkdir ~/.pomodoro_manager/sounds
    wget -o ~/.pomodoro_manager/sounds/alarm.ogg http://www.bigsoundbank.com/dl.php?ext=wav&id=0897&button=GO%3E
    sqlite3 ~/.pomodoro_manager/database.db "CREATE TABLE pomodoros( pomDate TEXT, pomTime TEXT )"
  fi
}

function load-variables {
  :
}

function record-pomodoro {
  dt=$(date +%Y-%m-%d)
  t=$(date +%H:%M)

  sqlite3 ~/.pomodoro_manager/database.db "INSERT INTO pomodoros VALUES( '$dt', '$t' )"
}

function cleanup {
  rm -f ~/.pomodoro_manager/*.txt
}

function alarm {
  if [ -z "$2" ]
  then
      comm=":"
  else
      comm=$2
  fi

  d=$(echo $1 | sed 's/s/sec/g' | sed 's/m/min/g')
  d=$(date -d "+$d" +%s)
  echo $d > ~/.pomodoro_manager/stopat.txt

  sleep $1 && cleanup && eval "$comm" && mplayer ~/.pomodoro_manager/sounds/alarm.ogg > /dev/null 2>&1 &
  p=$!
  echo $p > ~/.pomodoro_manager/pid.txt
}

function cancel-alarm {
  if [ -f ~/.pomodoro_manager/pid.txt ]
  then
      psleep=$(pgrep -P $(cat ~/.pomodoro_manager/pid.txt))
      kill $(cat ~/.pomodoro_manager/pid.txt) 2>/dev/null
      kill $psleep 2>/dev/null
      cleanup
  fi
}

function pomodoros-today {
  dt=$(date '+%Y-%m-%d')

  sqlite3 ~/.pomodoro_manager/database.db "SELECT pomTime FROM pomodoros WHERE pomDate = '$dt'" | awk -F ":" '
    BEGIN{
      morning=0;
      afternoon=0;
      evening=0;
    }

    {
      if( $1 <= 12 ){
        morning++;
      }else if( $1 > 12 && $1 <= 17 ){
        afternoon++;
      }else{
        evening++;
      }
    }

    END{
      print "Morning: " morning;
      print "Afternoon: " afternoon;
      print "Evening: " evening;
    }
  '
}

function remaining {
  if [ -f ~/.pomodoro_manager/stopat.txt ]
  then
      d1=$(date +%s)
      d2=$(cat ~/.pomodoro_manager/stopat.txt)

      remaining=$(($d2 - $d1))

      if [ $remaining -gt 60 ]
      then
          remaining=$(($remaining / 60))
          if [ $remaining -eq 1 ]
          then
              echo "1 minute left."
          else
              echo "$remaining minutes left."
          fi


      else
          echo "$remaining seconds left."
      fi

  fi
}

check-command sqlite3
check-command jq
check-working-directory
load-variables

case "$1" in
    start|s)
        cancel-alarm
        echo "Starting pomodoro."
        alarm 25m record-pomodoro
        ;;
    cancel|c)
        echo "Current pomodoro/break canceled."
        cancel-alarm
        ;;
    break|b)
        cancel-alarm
        echo "Starting short break."
        alarm 5m
        ;;
    long-break|lb)
        cancel-alarm
        echo "Starting long break."
        alarm 15m
        ;;
    time-left|l)
        remaining
        ;;
    today|t)
        pomodoros-today
        ;;
    *)
        echo "Usage: pomodoro start|cancel|break|long-break|time-left|today, or"
        echo "Usage: pomodoro s|c|b|lb|l|t."
        ;;
esac
