#!/bin/bash

if [ -f stopat.txt ]
then
    d1=$(date +%s)
    d2=$(cat stopat.txt)

    remaining=$(($d2 - $d1))

    if [ $remaining -gt 60 ]
    then
        remaining=$(($remaining / 60))
        if [ $remaining -eq 1 ]
        then
            echo "1 minute left."
        else
            echo "$remaining minutes left."
        fi


    else
        echo "$remaining seconds left."
    fi

fi

